//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_Data.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class frase
    {
        public int id { get; set; }
        public Nullable<int> id_pelicula { get; set; }
        public Nullable<int> id_actor { get; set; }
        public string frase1 { get; set; }
    
        public virtual actor actor { get; set; }
        public virtual pelicula pelicula { get; set; }
    }
}
